defaults: &defaults
  event:
    name: "elasticberlin Hackfest 2014"
    single_day: true
    start_time: 2014-05-28 09:00:00
    end_time: 2014-05-28 18:00:00
  host: "projects.elastic.berlin"
  mailers:
    from: "projects@elastic.berlin"
  errors:
    from: "exception@elastic.berlin"
    to:
      - "florian.gilcher@asquera.de"
      - "felix.gilcher@asquera.de"
  seo:
    title: "elasticsearch hackday projects"
    author: "eurucamp team"
    description: "List of companion events."

development:
  <<: *defaults
  host: "activities.dev:3000"

test:
  <<: *defaults

staging:
  <<: *defaults
  host: "activities-staging.eurucamp.org"

production:
  <<: *defaults
